### ISSUE TITLE
Doesn't work on Android 11 beta 3 :-(

### ISSUE THREAD

**Issue by ekeppel** [Magisk-Modules-Repo/HideNavBar#14]
Beta 3 appears to now detect when gesture navigation is disabled and defaults to one of the other methods, so this module no longer seems to work.

Device: Taimen (Pixel 2 XL)
Magisk Canary 20420

**Comment by DanGLES3** [comment]
Disable my module and send me the original gestures overlays that are on /product/overlay

**Comment by ekeppel** [comment]
Sorry for the delay.  Here you go:

[NavigationBarModeOverlays.zip](https://github.com/Magisk-Modules-Repo/HideNavBar/files/5178939/NavigationBarModeOverlays.zip)

**Comment by DanGLES3** [comment]
Should be fixed on the latest update 6.7

**Comment by pbanj** [comment]
i still get the 3 button nav bar. trying to use this with fluid navigation gestures and was hoping this would get rid of the 3 button nave bar. i really regret updating to 11 lol

**Comment by DanGLES3** [comment]
> i still get the 3 button nav bar. trying to use this with fluid navigation gestures and was hoping this would get rid of the 3 button nave bar. i really regret updating to 11 lol

Could you try uninstalling and reinstalling my module? It worked fine for another user that tried it

**Comment by pbanj** [comment]
let me try

**Comment by pbanj** [comment]
nope still there. should i be telling fng to hide the nav bar still or not?

**Comment by DanGLES3** [comment]
> nope still there. should i be telling fng to hide the nav bar still or not?

No, also is the gestures option still gone for you?

**Comment by pbanj** [comment]
the gesture options in system settings? thats there. just told it not to try and hide, reinstalled your mod and the bar is still there. im on a pixel 3a if that helps at all

**Comment by DanGLES3** [comment]
> the gesture options in system settings? thats there. just told it not to try and hide, reinstalled your mod and the bar is still there. im on a pixel 3a if that helps at all

So, did you enable the gestures?

**Comment by pbanj** [comment]
> 
> 
> > the gesture options in system settings? thats there. just told it not to try and hide, reinstalled your mod and the bar is still there. im on a pixel 3a if that helps at all
> 
> So, did you enable the gestures?

enabling them makes it go full screen but fluid navigation gestures doesnt work. just the stock gestures

**Comment by pbanj** [comment]
what im trying to use https://play.google.com/store/apps/details?id=com.fb.fluid&hl=en_US

**Comment by DanGLES3** [comment]
> > 
> > 
> > > the gesture options in system settings? thats there. just told it not to try and hide, reinstalled your mod and the bar is still there. im on a pixel 3a if that helps at all
> > 
> > So, did you enable the gestures?
> 
> enabling them makes it go full screen but fluid navigation gestures doesnt work. just the stock gestures

Then that's not really an issue with my module tbh, that's an fluid NG issue, iirc it isn't yet compatible with Android 11

**Comment by pbanj** [comment]
ya was hoping your mod would be able to hide it at least until they updated

**Comment by DanGLES3** [comment]
> ya was hoping your mod would be able to hide it at least until they updated

My mod was only designed to hide the gesture bar, if you want to hide the 3 button navbar then add this to your build.prop qemu.hw.mainkeys=1

**Comment by DanGLES3** [comment]
Fluid can no longer hide the navbar because Google removed the overscan command on Android 11

**Comment by pbanj** [comment]
> 
> 
> > ya was hoping your mod would be able to hide it at least until they updated
> 
> My mod was only designed to hide the gesture bar, if you want to hide the 3 button navbar then add this to your build.prop qemu.hw.mainkeys=1

oooo ill have to give that a try

> 
> 
> Fluid can no longer hide the navbar because Google removed the overscan command on Android 11

ya i knew that part

**Comment by pbanj** [comment]
> qemu.hw.mainkeys=1

it worked you, i could hug you
